# Generated by Django 3.0.3 on 2020-03-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travel',
            name='date_travel',
        ),
        migrations.AddField(
            model_name='travel',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='travel',
            name='date_start',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
