# Generated by Django 3.0.3 on 2020-03-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200320_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='nb_people',
            field=models.IntegerField(null=True),
        ),
    ]
