# Generated by Django 3.0.3 on 2020-03-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_travel_nb_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='reference',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
