# Generated by Django 3.0.3 on 2020-03-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200320_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Disponible'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='date_end',
            field=models.DateField(null=True, verbose_name='Date dre retour'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='date_start',
            field=models.DateField(null=True, verbose_name='Date de départ'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='destination',
            field=models.CharField(max_length=50, verbose_name='Destination'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='nb_people',
            field=models.IntegerField(null=True, verbose_name='Nombre de personnes'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='price',
            field=models.IntegerField(verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='reference',
            field=models.IntegerField(null=True, unique=True, verbose_name='Référence'),
        ),
    ]
