# Generated by Django 3.0.3 on 2020-03-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200322_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='picture_min',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
