# Generated by Django 3.0.3 on 2020-03-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_travel_picture_min'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Réservation', 'verbose_name_plural': 'Réservations'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='travel',
            options={'verbose_name': 'Voyage', 'verbose_name_plural': 'Voyages'},
        ),
        migrations.RemoveField(
            model_name='travel',
            name='picture_min',
        ),
        migrations.AddField(
            model_name='booking',
            name='contacted',
            field=models.BooleanField(default=False, verbose_name='Demande traitée ?'),
        ),
    ]
